name: PHP CI

on:
  pull_request:
    branches:
      - main

jobs:
  revisar-sintaxis:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Revisar sintaxis de index.php
        run: php -l index.php

      - name: Revisar sintaxis de guardar.php
        run: php -l guardar.php
